[package]
name = "camera"
version = "0.1.0"
edition = "2021"
description = "Camera Interface for multiple camera types"
readme = "README.md"
license-file = "LICENSE"


# See more keys and their definitions at 
# https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "camera"


[profile.test]
opt-level = 3

[dependencies]
libc = "0.2.175"
thiserror = "2.0.16"
chrono = "0.4.42"
png = "0.18.0"
num-traits = "0.2.19"
rand = "0.9.2"
rand_distr = "0.5.1"
bytemuck = "1.23.2"
numeris = { path = "../numeris" }

[features]
svbony = []
